// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RiskFreeService.proto

package RiskFree;

public interface positionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:positions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string position = 1;</code>
   */
  java.lang.String getPosition();
  /**
   * <code>string position = 1;</code>
   */
  com.google.protobuf.ByteString
      getPositionBytes();
}
