// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RiskFreeService.proto

package RiskFree;

public interface requestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:request)
    com.google.protobuf.MessageOrBuilder {
}
