// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RiskFreeService.proto

package RiskFree;

public final class RiskFreeImpl {
  private RiskFreeImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_positions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_positions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_thanks_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_thanks_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Safe_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Safe_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025RiskFreeService.proto\"\035\n\tpositions\022\020\n\010" +
      "position\030\001 \001(\t\"\027\n\006thanks\022\r\n\005thank\030\001 \001(\t\"" +
      "\t\n\007request\"\024\n\004Safe\022\014\n\004safe\030\001 \001(\0102\202\001\n\010Ris" +
      "kFree\022\'\n\016covidPositions\022\n.positions\032\007.th" +
      "anks(\001\022#\n\tsafeZones\022\010.request\032\n.position" +
      "s0\001\022(\n\017insideSafeZones\022\n.positions\032\005.Saf" +
      "e(\0010\001B\032\n\010RiskFreeB\014RiskFreeImplP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_positions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_positions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_positions_descriptor,
        new java.lang.String[] { "Position", });
    internal_static_thanks_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_thanks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_thanks_descriptor,
        new java.lang.String[] { "Thank", });
    internal_static_request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_request_descriptor,
        new java.lang.String[] { });
    internal_static_Safe_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Safe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Safe_descriptor,
        new java.lang.String[] { "Safe", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
