// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RiskFreeService.proto

package RiskFree;

public interface SafeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Safe)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool safe = 1;</code>
   */
  boolean getSafe();
}
