// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RiskFreeService.proto

package RiskFree;

public interface thanksOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thanks)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string thank = 1;</code>
   */
  java.lang.String getThank();
  /**
   * <code>string thank = 1;</code>
   */
  com.google.protobuf.ByteString
      getThankBytes();
}
