// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VaccinationService.proto

package Vaccination;

public interface hadVaccinationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hadVaccination)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool vaccination = 1;</code>
   */
  boolean getVaccination();
}
