// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VaccinationService.proto

package Vaccination;

public interface requestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:request)
    com.google.protobuf.MessageOrBuilder {
}
