// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CovidFreeService.proto

package CovidFree;

public final class CovidFreeImpl {
  private CovidFreeImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_symptoms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_symptoms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_risk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_risk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hadCovid_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hadCovid_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026CovidFreeService.proto\"@\n\010symptoms\022\020\n\010" +
      "symptom1\030\001 \001(\t\022\020\n\010symptom2\030\002 \001(\t\022\020\n\010symp" +
      "tom3\030\003 \001(\t\"\031\n\004risk\022\021\n\triskValue\030\001 \001(\005\"\024\n" +
      "\006userId\022\n\n\002id\030\001 \001(\005\"\031\n\010hadCovid\022\r\n\005covid" +
      "\030\001 \001(\0102U\n\tCovidFree\022#\n\017risk_calculator\022\t" +
      ".symptoms\032\005.risk\022#\n\rcovid_history\022\007.user" +
      "Id\032\t.hadCovidB\034\n\tCovidFreeB\rCovidFreeImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_symptoms_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_symptoms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_symptoms_descriptor,
        new java.lang.String[] { "Symptom1", "Symptom2", "Symptom3", });
    internal_static_risk_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_risk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_risk_descriptor,
        new java.lang.String[] { "RiskValue", });
    internal_static_userId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_userId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_hadCovid_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_hadCovid_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hadCovid_descriptor,
        new java.lang.String[] { "Covid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
