// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CovidFreeService.proto

package CovidFree;

public interface hadCovidOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hadCovid)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool covid = 1;</code>
   */
  boolean getCovid();
}
