// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CovidFreeService.proto

package CovidFree;

public interface riskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:risk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 riskValue = 1;</code>
   */
  int getRiskValue();
}
