// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CovidFreeService.proto

package CovidFree;

/**
 * Protobuf type {@code symptoms}
 */
public  final class symptoms extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:symptoms)
    symptomsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use symptoms.newBuilder() to construct.
  private symptoms(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private symptoms() {
    symptom1_ = "";
    symptom2_ = "";
    symptom3_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private symptoms(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            symptom1_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            symptom2_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            symptom3_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CovidFree.CovidFreeImpl.internal_static_symptoms_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CovidFree.CovidFreeImpl.internal_static_symptoms_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CovidFree.symptoms.class, CovidFree.symptoms.Builder.class);
  }

  public static final int SYMPTOM1_FIELD_NUMBER = 1;
  private volatile java.lang.Object symptom1_;
  /**
   * <code>string symptom1 = 1;</code>
   */
  public java.lang.String getSymptom1() {
    java.lang.Object ref = symptom1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symptom1_ = s;
      return s;
    }
  }
  /**
   * <code>string symptom1 = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSymptom1Bytes() {
    java.lang.Object ref = symptom1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symptom1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYMPTOM2_FIELD_NUMBER = 2;
  private volatile java.lang.Object symptom2_;
  /**
   * <code>string symptom2 = 2;</code>
   */
  public java.lang.String getSymptom2() {
    java.lang.Object ref = symptom2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symptom2_ = s;
      return s;
    }
  }
  /**
   * <code>string symptom2 = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSymptom2Bytes() {
    java.lang.Object ref = symptom2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symptom2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYMPTOM3_FIELD_NUMBER = 3;
  private volatile java.lang.Object symptom3_;
  /**
   * <code>string symptom3 = 3;</code>
   */
  public java.lang.String getSymptom3() {
    java.lang.Object ref = symptom3_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symptom3_ = s;
      return s;
    }
  }
  /**
   * <code>string symptom3 = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSymptom3Bytes() {
    java.lang.Object ref = symptom3_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symptom3_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSymptom1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symptom1_);
    }
    if (!getSymptom2Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, symptom2_);
    }
    if (!getSymptom3Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, symptom3_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSymptom1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symptom1_);
    }
    if (!getSymptom2Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, symptom2_);
    }
    if (!getSymptom3Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, symptom3_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CovidFree.symptoms)) {
      return super.equals(obj);
    }
    CovidFree.symptoms other = (CovidFree.symptoms) obj;

    boolean result = true;
    result = result && getSymptom1()
        .equals(other.getSymptom1());
    result = result && getSymptom2()
        .equals(other.getSymptom2());
    result = result && getSymptom3()
        .equals(other.getSymptom3());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SYMPTOM1_FIELD_NUMBER;
    hash = (53 * hash) + getSymptom1().hashCode();
    hash = (37 * hash) + SYMPTOM2_FIELD_NUMBER;
    hash = (53 * hash) + getSymptom2().hashCode();
    hash = (37 * hash) + SYMPTOM3_FIELD_NUMBER;
    hash = (53 * hash) + getSymptom3().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CovidFree.symptoms parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CovidFree.symptoms parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CovidFree.symptoms parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CovidFree.symptoms parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CovidFree.symptoms parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CovidFree.symptoms parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CovidFree.symptoms parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CovidFree.symptoms parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CovidFree.symptoms parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CovidFree.symptoms parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CovidFree.symptoms parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CovidFree.symptoms parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CovidFree.symptoms prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code symptoms}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:symptoms)
      CovidFree.symptomsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CovidFree.CovidFreeImpl.internal_static_symptoms_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CovidFree.CovidFreeImpl.internal_static_symptoms_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CovidFree.symptoms.class, CovidFree.symptoms.Builder.class);
    }

    // Construct using CovidFree.symptoms.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      symptom1_ = "";

      symptom2_ = "";

      symptom3_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CovidFree.CovidFreeImpl.internal_static_symptoms_descriptor;
    }

    @java.lang.Override
    public CovidFree.symptoms getDefaultInstanceForType() {
      return CovidFree.symptoms.getDefaultInstance();
    }

    @java.lang.Override
    public CovidFree.symptoms build() {
      CovidFree.symptoms result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public CovidFree.symptoms buildPartial() {
      CovidFree.symptoms result = new CovidFree.symptoms(this);
      result.symptom1_ = symptom1_;
      result.symptom2_ = symptom2_;
      result.symptom3_ = symptom3_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CovidFree.symptoms) {
        return mergeFrom((CovidFree.symptoms)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CovidFree.symptoms other) {
      if (other == CovidFree.symptoms.getDefaultInstance()) return this;
      if (!other.getSymptom1().isEmpty()) {
        symptom1_ = other.symptom1_;
        onChanged();
      }
      if (!other.getSymptom2().isEmpty()) {
        symptom2_ = other.symptom2_;
        onChanged();
      }
      if (!other.getSymptom3().isEmpty()) {
        symptom3_ = other.symptom3_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CovidFree.symptoms parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CovidFree.symptoms) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object symptom1_ = "";
    /**
     * <code>string symptom1 = 1;</code>
     */
    public java.lang.String getSymptom1() {
      java.lang.Object ref = symptom1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symptom1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string symptom1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSymptom1Bytes() {
      java.lang.Object ref = symptom1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symptom1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symptom1 = 1;</code>
     */
    public Builder setSymptom1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      symptom1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string symptom1 = 1;</code>
     */
    public Builder clearSymptom1() {
      
      symptom1_ = getDefaultInstance().getSymptom1();
      onChanged();
      return this;
    }
    /**
     * <code>string symptom1 = 1;</code>
     */
    public Builder setSymptom1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      symptom1_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object symptom2_ = "";
    /**
     * <code>string symptom2 = 2;</code>
     */
    public java.lang.String getSymptom2() {
      java.lang.Object ref = symptom2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symptom2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string symptom2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSymptom2Bytes() {
      java.lang.Object ref = symptom2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symptom2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symptom2 = 2;</code>
     */
    public Builder setSymptom2(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      symptom2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string symptom2 = 2;</code>
     */
    public Builder clearSymptom2() {
      
      symptom2_ = getDefaultInstance().getSymptom2();
      onChanged();
      return this;
    }
    /**
     * <code>string symptom2 = 2;</code>
     */
    public Builder setSymptom2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      symptom2_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object symptom3_ = "";
    /**
     * <code>string symptom3 = 3;</code>
     */
    public java.lang.String getSymptom3() {
      java.lang.Object ref = symptom3_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symptom3_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string symptom3 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSymptom3Bytes() {
      java.lang.Object ref = symptom3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symptom3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symptom3 = 3;</code>
     */
    public Builder setSymptom3(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      symptom3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string symptom3 = 3;</code>
     */
    public Builder clearSymptom3() {
      
      symptom3_ = getDefaultInstance().getSymptom3();
      onChanged();
      return this;
    }
    /**
     * <code>string symptom3 = 3;</code>
     */
    public Builder setSymptom3Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      symptom3_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:symptoms)
  }

  // @@protoc_insertion_point(class_scope:symptoms)
  private static final CovidFree.symptoms DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CovidFree.symptoms();
  }

  public static CovidFree.symptoms getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<symptoms>
      PARSER = new com.google.protobuf.AbstractParser<symptoms>() {
    @java.lang.Override
    public symptoms parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new symptoms(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<symptoms> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<symptoms> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public CovidFree.symptoms getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

