// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CovidFreeService.proto

package CovidFree;

public interface symptomsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:symptoms)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symptom1 = 1;</code>
   */
  java.lang.String getSymptom1();
  /**
   * <code>string symptom1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getSymptom1Bytes();

  /**
   * <code>string symptom2 = 2;</code>
   */
  java.lang.String getSymptom2();
  /**
   * <code>string symptom2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getSymptom2Bytes();

  /**
   * <code>string symptom3 = 3;</code>
   */
  java.lang.String getSymptom3();
  /**
   * <code>string symptom3 = 3;</code>
   */
  com.google.protobuf.ByteString
      getSymptom3Bytes();
}
